screenshot: Generate bitmaps from bmpblk
Instead of checking in prebuilt bitmaps, which easily get out of sync
with bmpblk, generate them from bmpblk at build time for `make
screenshot` and `make test-screenshot`. The bmpblk source is located
at ../bmpblk by default, and can be overridden by BMPBLK_SOURCE. The
bitmaps are generated with the "screenshot" board config and the "en"
locale only, and are regenerated only when bmpblk sources change.

Setting BMP_PATH still allows using a custom bitmap directory, in which
case bmpblk is not built.

Remove screenshot/bmp.

BUG=b:551743258
BRANCH=none
TEST=make test-screenshot
TAG=agy
CONV=4d411a1c-369f-4fd3-ac8a-7bd726afa3b5

Cq-Depend: chromium:8459506, chromium:8460922
Change-Id: I045f291991dac86c7f675507ab5c7e366a6a6964
Signed-off-by: Yu-Ping Wu <yupingso@google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/depthcharge/+/8460942
Reviewed-by: Chen-Tsung Hsieh <chentsung@chromium.org>
Tested-by: Yu-Ping Wu <yupingso@chromium.org>
SLSA-Policy-Verified: SLSA Policy Verification Service <devtools-gerritcodereview-exitgate@google.com>
Commit-Queue: Yu-Ping Wu <yupingso@chromium.org>

diff --git a/screenshot/Makefile.inc b/screenshot/Makefile.inc
--- a/screenshot/Makefile.inc
+++ b/screenshot/Makefile.inc
@@ -27,8 +27,18 @@ LOG ?=
 override LOG := \"$(LOG)\"
 LOG_FILE ?=
 override LOG_FILE := \"$(LOG_FILE)\"
-BMP_PATH ?= $(screenshotsrc)/bmp
+
+# Unless BMP_PATH is specified, bitmaps are generated from bmpblk.
+BMPBLK_SOURCE ?= $(abspath $(src)/../bmpblk)
+BMPBLK_BOARD ?= screenshot
+bmpblk-out := $(testobj)/bmpblk
+bmpblk-stamp := $(bmpblk-out)/.stamp
+ifeq ($(origin BMP_PATH),undefined)
+BMP_PATH := $(bmpblk-out)/$(BMPBLK_BOARD)
+screenshot-bmp-deps := $(bmpblk-stamp)
+endif
 override BMP_PATH := \"$(BMP_PATH)\"
+
 OUTPUT ?= $(screenshotobj)/$(SCREEN).bmp
 
 SCREENSHOT_OPTIONS += WIDTH HEIGHT SCREEN ITEM
@@ -114,7 +124,22 @@ OUTPUT_RAW := $(screenshotobj)/$(notdir $(basename $(OUTPUT))).raw
 
 .PHONY: screenshot test-screenshot clean-screenshot
 
-screenshot: $(screenshot-bin)
+bmpblk-srcs := $(shell find $(BMPBLK_SOURCE) \
+	\( -name build -o -name '.*' -o -name __pycache__ \) -prune -o \
+	-type f -print 2>/dev/null)
+
+$(bmpblk-stamp): $(bmpblk-srcs)
+	@if [ ! -d "$(BMPBLK_SOURCE)" ]; then \
+		echo "bmpblk not found in $(BMPBLK_SOURCE);" \
+			"please set BMPBLK_SOURCE or BMP_PATH" >&2; \
+		exit 1; \
+	fi
+	rm -rf $(bmpblk-out)
+	$(MAKE) -C $(BMPBLK_SOURCE) BOARD=$(BMPBLK_BOARD) LOCALES=en \
+		OUTPUT=$(bmpblk-out)
+	touch $@
+
+screenshot: $(screenshot-bin) $(screenshot-bmp-deps)
 	$(screenshot-bin) $(OUTPUT_RAW)
 	$(screenshotsrc)/raw2bmp.py $(WIDTH) $(HEIGHT) $(OUTPUT_RAW) $(OUTPUT)
 	@echo Screenshot saved to $(OUTPUT)
