tests: Change libpayload arch to ARCH_MOCK and remove x86_32 limitation
This patch changes libpayload architecture to ARCH_MOCK to free
depthcharge unit-tests from x86_32 requirement. It also adds mocks for
timer_raw_value() and timer_hz() required to correctly link libpayload
with test binary. The endianness of libpayload build is set using
endian_test program ported from QEMU configure script.

This patch also fixes potential issues with:
- multiple inclusion of config.h file, which lacked include-guards,
- incorrect splitconfig path (missing slash at the end),
- unnecessary src/arch/x86/include path in includes list (removed),

BUG=b:192915012
TEST=sudo emerge dev-util/cmocka ; make unit-tests
BRANCH=none

Signed-off-by: Jakub Czapiga <jacz@semihalf.com>
Change-Id: I9df91017c1f57701084618ac6a40569304ffb8e3
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/depthcharge/+/3178281
Auto-Submit: Jakub Czapiga <czapiga@google.com>
Reviewed-by: Yu-Ping Wu <yupingso@chromium.org>
Commit-Queue: Jakub Czapiga <czapiga@google.com>
Tested-by: Jakub Czapiga <czapiga@google.com>

diff --git a/tests/Makefile.inc b/tests/Makefile.inc
--- a/tests/Makefile.inc
+++ b/tests/Makefile.inc
@@ -38,7 +38,7 @@ LIBPAYLOAD_DOTCONFIG := $(libpayloadobj)/.config
 LIBPAYLOAD_KCONFIG_AUTOHEADER := $(libpayloadobj)/config.h
 LIBPAYLOAD_KCONFIG_AUTOCONFIG := $(libpayloadobj)/auto.conf
 LIBPAYLOAD_KCONFIG_DEPENDENCIES := $(libpayloadobj)/auto.conf.cmd
-LIBPAYLOAD_KCONFIG_SPLITCONFIG := $(libpayloadobj)/config
+LIBPAYLOAD_KCONFIG_SPLITCONFIG := $(libpayloadobj)/config/
 LIBPAYLOAD_KCONFIG_TRISTATE := $(libpayloadobj)/tristate.conf
 LIBPAYLOAD_CONFIG := $(libpayloadobj)/libpayload-config.h
 
@@ -46,14 +46,14 @@ CMAKE := cmake
 OBJCOPY ?= objcopy
 OBJDUMP ?= objdump
 
-TEST_CFLAGS := -m32
-TEST_LDFLAGS := -m32
+TEST_CFLAGS :=
+TEST_LDFLAGS :=
 
 # Include generic test mock headers, before original ones
 TEST_CFLAGS += -I$(testsrc)/include/mocks -I$(testsrc)/include
 
 # Depthcharge includes
-TEST_CFLAGS += -I$(obj) -I$(src)/src -I$(src)/src/arch/x86/includes/
+TEST_CFLAGS += -I$(obj) -I$(src)/src
 
 # vboot_reference and ec-headers
 TEST_CFLAGS += -I$(VB_SOURCE)/firmware/include -I$(EC_HEADERS)
@@ -61,7 +61,7 @@ TEST_CFLAGS += -I$(VB_SOURCE)/firmware/include -I$(EC_HEADERS)
 # Libpayload flags
 TEST_CFLAGS += -D__LIBPAYLOAD__=1
 TEST_CFLAGS += -I$(libpayloadobj)
-TEST_CFLAGS += -I$(libpayloadsrc)/include -I $(libpayloadsrc)/include/x86
+TEST_CFLAGS += -I$(libpayloadsrc)/include -I $(libpayloadsrc)/include/mock
 TEST_CFLAGS += -include $(libpayloadsrc)/include/kconfig.h
 TEST_CFLAGS += -include $(libpayloadsrc)/include/compiler.h
 
@@ -108,6 +108,7 @@ $(call evaluate_subdirs)
 default_mocks-srcs := src/vboot/callbacks/debug.c \
 	tests/mocks/console.c \
 	tests/mocks/halt.c \
+	tests/mocks/timer.c \
 	tests/mocks/util/commonparams.c
 default_mocks := commonparams console_write halt vb2ex_abort vb2ex_printf
 
@@ -121,13 +122,16 @@ define TEST_CC_template
 $(1)-config-file := $(obj)/$(1)/config.h
 $$($(1)-config-file):
 	mkdir -p $$(dir $$@)
-	printf '// File generated by tests/Makefile.inc\n// Do not change\n' > $$@
+	printf '// File generated by tests/Makefile.inc\n// Do not change\n\n' > $$@;
+	printf '#ifndef TEST_DEPTHCHARGE_CONFIG_H_\n' >> $$@;
+	printf '#define TEST_DEPTHCHARGE_CONFIG_H_\n' >> $$@;
 	for kv in $$($(1)-config); do \
 		key="`echo $$$$kv | cut -d '=' -f -1`"; \
 		value="`echo $$$$kv | cut -d '=' -f 2-`"; \
 		printf '#undef %s\n' "$$$$key" >> $$@; \
 		printf '#define %s %s\n\n' "$$$$key" "$$$$value" >> $$@; \
 	done
+	printf '#endif\n' >> $$@;
 
 $(1)-mocks += $(default_mocks)
 
@@ -206,8 +210,17 @@ DEPENDENCIES += $(addsuffix .d,$(basename $(all-test-objs)))
 $(LIBPAYLOAD_DOTCONFIG):
 	mkdir -p $(dir $@)
 	cp $(LIBPAYLOAD_DEFCONFIG) $@
-	printf '\nCONFIG_LP_CHROMEOS=y\n' >> $@
-	printf '\nCONFIG_LP_ARCH_X86=y\n' >> $@
+	printf '\nCONFIG_LP_CHROMEOS=y\n' >> $@;
+	printf '\nCONFIG_LP_ARCH_MOCK=y\n' >> $@;
+	byte_order="x`python -c 'import sys; print(sys.byteorder)' 2>&1`"; \
+	if [ "$$byte_order" == "xbig" ] ; then \
+		printf '\nCONFIG_LP_ARCH_MOCK_BIG_ENDIAN=y\n' >> $@; \
+	elif [ "$$byte_order" == "xlittle" ] ; then \
+		printf '\nCONFIG_LP_ARCH_MOCK_BIG_ENDIAN=n\n' >> $@; \
+	else \
+		echo 'Failed to get machine byte order'; \
+		exit 1; \
+	fi
 
 $(LIBPAYLOAD_KCONFIG_AUTOHEADER): LIBPAYLOAD_KCONFIG_FLAGS := \
 	DOTCONFIG=$(LIBPAYLOAD_DOTCONFIG) \
@@ -229,8 +242,8 @@ $(LIBPAYLOAD_LIB): $(LIBPAYLOAD_KCONFIG_AUTOHEADER)
 	@printf "    MAKE       $(subst $(obj)/,,$(@))\n"
 	+unset CFLAGS && $(MAKE) -C $(libpayloadsrc) \
 		HOSTCC=$(HOSTCC) CC=$(HOSTCC) CXX=$(HOSTCXX) AR=$(HOSTAR) AS=$(HOSTAS) \
-		EXTRA_CFLAGS=-m32 obj=$(libpayloadobj) \
-		DOTCONFIG=$(LIBPAYLOAD_DOTCONFIG) V=$(V)
+		obj=$(libpayloadobj) DOTCONFIG=$(LIBPAYLOAD_DOTCONFIG) V=$(V) \
+		EXTRA_CFLAGS="-Wno-address-of-packed-member"
 
 $(LIBPAYLOAD_CONFIG): $(LIBPAYLOAD_KCONFIG_AUTOHEADER)
 	mkdir -p $(dir $@)
@@ -241,7 +254,7 @@ $(VBOOT_LIB):
 	@printf "    MAKE       $(subst $(obj)/,,$(@))\n"
 	FIRMWARE_ARCH= \
 		CC="$(HOSTCC)" \
-		CFLAGS="-m32 -DVBOOT_DEBUG" \
+		TEST_PRINT=$(TEST_PRINT) \
 		$(MAKE) -C $(VB_SOURCE) \
 		MOCK_TPM= \
 		TPM2_MODE=1 \
